version: '3.3'

services:

  redis:
    image: redis:6.2.3
    restart: unless-stopped
    ports:
      - 6379:6379

  bupa:
    build: .
    restart: unless-stopped
    ports:
      - 5001:8080
    environment:
      - TRAINER_TELEMETRY=0
      - REIDS_HOST=redis
    links:
      - redis
    depends_on:
      - redis

  ngrok:
    image: wernight/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTH: 2QKOQOVRQDyblUWY3njeIgPDtZu_6sAbZvocvzJJLq8qaHXz6
      NGROK_PROTOCOL: https
      NGROK_PORT: bupa:8080
    ports:
      - 4040:4040
    links:
      - bupa
    depends_on:
      - bupa