version: '3.3'

services:
  bupa:
    build: .
    restart: unless-stopped
    ports:
      - 5001:8080
    environment:
      - TRAINER_TELEMETRY=0

  ngrok:
    image: wernight/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTH: 
      NGROK_PROTOCOL: https
      NGROK_PORT: bupa:8080
    ports:
      - 4040:4040
    links:
      - bupa
    depends_on:
      - bupa